In [11]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [12]:
df = pd.read_csv( '../data/feature eng data/feature_eng_data.csv' )

# Encoding Categorical Columns

### * Encoding ordinal columns using Label Encoding

In [13]:
df.sample()

,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score,course_diff
3747,male,Bachelor of Computer Applications,2.73,74.9,no,6.8,poor,online videos,low,easy,47.9,4

### columns to label encode :
 'sleep_quality', 'facility_rating', 'exam_difficulty'

In [14]:
df['exam_difficulty'].unique()

<ArrowStringArray>
['hard', 'moderate', 'easy']
Length: 3, dtype: str

In [15]:
def encode_sleep_quality( df ) :
    df['sleep_quality'] = df['sleep_quality'].map({
        'poor' : 0, 'average' : 1, 'good' : 2
    })
    return df
    
df = encode_sleep_quality( df )

In [16]:
def encode_facility_rating( df ) :
    df['facility_rating'] = df['facility_rating'].map({
        'low' : 0, 'medium' : 1, 'high' : 2
    })
    return df
    
df = encode_facility_rating( df )

In [17]:
def encode_exam_difficulty( df ) :
    df['exam_difficulty'] = df['exam_difficulty'].map({
        'easy' : 0, 'moderate' : 1, 'hard' : 2
    })
    return df
    
df = encode_exam_difficulty( df )

In [18]:
df.sample()

,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score,course_diff
8222,male,Diploma,4.06,73.8,yes,9.0,2,self-study,1,0,76.4,0

In [19]:
df.shape

(20000, 12)

### columns to one-hot encode :
 'gender', 'course', 'internet_access', 'study_method'

In [20]:
df = pd.get_dummies( df, 
               columns = ['gender', 'course', 'internet_access', 'study_method'],
               dtype = int)
df

,study_hours,class_attendance,sleep_hours,sleep_quality,facility_rating,exam_difficulty,exam_score,course_diff,gender_female,gender_male,...,course_Bachelor of Science,course_Bachelor of Technology,course_Diploma,internet_access_no,internet_access_yes,study_method_coaching,study_method_group study,study_method_mixed,study_method_online videos,study_method_self-study
0,2.78,92.9,7.4,0,0,2,58.9,0,0,1,...,0,0,1,0,1,1,0,0,0,0
1,3.37,64.8,4.6,1,1,1,54.8,4,0,0,...,0,0,0,0,1,0,0,0,1,0
2,7.88,76.8,8.5,0,2,1,90.3,5,0,1,...,1,0,0,0,1,1,0,0,0,0
3,0.67,48.4,5.8,1,0,1,29.7,0,0,0,...,0,0,1,0,1,0,0,0,1,0
4,0.89,71.6,9.8,0,0,1,43.7,0,1,0,...,0,0,1,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,6.50,71.3,5.0,2,0,0,86.5,3,0,0,...,0,0,0,0,1,0,0,0,0,1
19996,3.71,41.6,5.9,1,1,1,60.9,2,0,1,...,0,0,0,1,0,1,0,0,0,0
19997,7.88,68.2,4.6,0,0,0,64.5,0,0,0,...,0,0,1,0,1,0,1,0,0,0
19998,4.60,76.3,6.1,2,1,1,79.0,3,0,1,...,0,0,0,1,0,0,0,0,0,1
19999,7.50,47.9,7.5,0,1,1,71.0,5,0,1,...,1,0,0,0,1,1,0,0,0,0

In [21]:
df.to_csv( '../data/preprocessed data/pre-processed_data.csv', index = False )